=== GurinderGirn/ticket-support-system/xsd/ticket.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <!--support ticket schema start  -->
  <xs:element name="supportticket">
    <xs:complexType>
	  <xs:sequence>
	    <!--ticket element start -->
		<xs:element name="ticket" minOccurs="0" maxOccurs="unbounded">
		  <xs:complexType>
		    <xs:sequence>
			  <!--ticket elements start -->
			    <xs:element name="dateOfIssue" type="xs:date" />
				<xs:element name="resolvedDate" type="xs:date" minOccurs="0" />
				<xs:element name="clientId" type="clientId" />
				<xs:element name="staffId" type="staffId" />
				<xs:element name="supportMessages">
				  <xs:complexType>
				    <xs:sequence>
					  <xs:element name="message" maxOccurs="unbounded" />
					</xs:sequence>
					<xs:attribute name="msgDate" type="xs:date" />
					<xs:attribute name="userId" type="clientId" />
				  </xs:complexType>
				</xs:element>
			  <!-- ticket elements end -->
			</xs:sequence>
			<!-- attribute list start-->
			<xs:attribute name="ticketNumber" type="number" use="required" />
			<xs:attribute name="category" type="xs:string" use="required" />
			<xs:attribute name="status" type="status" use="required" />
			<!--attribute list end -->
		  </xs:complexType>
		</xs:element>
		<!--ticket element end -->
	  </xs:sequence>
	</xs:complexType>  
  </xs:element>
  <!--support ticket schema end -->
  <!-- user defined data types -->
  <xs:simpleType name="number">
    <xs:restriction base="xs:string">
	  <xs:pattern value="\d+" />
	</xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="status">
    <xs:restriction base="xs:string">
	  <xs:enumeration value="on-going" />
	  <xs:enumeration value="resolved" />
	</xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="clientId">
    <xs:restriction base="xs:string">
	  <xs:pattern value="\d+" />
	</xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="staffId">
    <xs:restriction base="xs:string">
	  <xs:pattern value="\d+" />
	</xs:restriction>
  </xs:simpleType>

</xs:schema>

=== GurinderGirn/ticket-support-system/xml/ticket.xml
<?xml version="1.0" encoding="utf-8"?>
<supportticket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/ticket.xsd">
  <ticket ticketNumber="101" category="technical" status="on-going">
    <dateOfIssue>2018-02-01</dateOfIssue>
    <clientId>102</clientId>
    <staffId>101</staffId>
    <supportMessages>
      <message msgDate="2018-02-02" userId="102">I would like to know about technical issues regarding software that i have downloaded.</message>
      <message msgDate="2018-02-03" userId="101">Thank You for using software. would you please tell us detail of software.</message>
    </supportMessages>
  </ticket>
  <ticket ticketNumber="102" category="sales" status="on-going">
    <dateOfIssue>2018-02-11</dateOfIssue>
    <clientId>102</clientId>
    <staffId>101</staffId>
    <supportMessages>
      <message msgDate="2018-02-12" userId="102">I want to download a XYZ software. would you tell me price for software.</message>
      <message msgDate="2018-02-13" userId="101">I would like to know version of software that you want to download.</message>
    </supportMessages>
  </ticket>
  <ticket ticketNumber="103" category="maintenance" status="resolved">
    <dateOfIssue>2018-01-28</dateOfIssue>
    <resolvedDate>2018-02-10</resolvedDate>
    <clientId>104</clientId>
    <staffId>103</staffId>
    <supportMessages>
      <message msgDate="2018-01-29" userId="104">Is there any maintenance charges for XYZ software?</message>
      <message msgDate="2018-01-30" userId="103">No, there are not any maintenance charges associated with softwares.</message>
      <message msgDate="2018-01-30" userId="103">Your issue has been resolved and ticket status is set to resolved.</message>
    </supportMessages>
  </ticket>
  <ticket ticketNumber="104" category="maintenance" status="on-going">
    <dateOfIssue>2018-01-28</dateOfIssue>
    <resolvedDate>2018-02-10</resolvedDate>
    <clientId>104</clientId>
    <staffId>103</staffId>
    <supportMessages>
      <message msgDate="2018-01-29" userId="104">Is there any maintenance charges for XYZ software?</message>
      <message msgDate="2018-01-30" userId="103">No, there are not any maintenance charges associated with softwares.</message>
    </supportMessages>
  </ticket>

</supportticket>
